# Setup
title: Bearnardd's log
url: https://bearnardd.github.io/
paginate: 1
paginate_path: "/bearnardd-log/page:num/"
baseurl: "/bearnardd-log"
permalink: pretty


markdown: kramdown
highlighter: rouge
  # input: GFM

# markdown:
#     auto_ids: true

kramdown:
  auto_ids: true

# Gems
plugins:
  - jekyll-include-cache
  - gemfile
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag




# Optimize Jekyll

include:
 - assets

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Bearnardd
  url: https://github.com/bearnardd
  email: bartek.szmelczynski@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /bearnardd-log/archive

  - title: About
    url: /bearnardd-log/about
